### ISSUE TITLE
CMVS translator issues

### ISSUE THREAD

**Issue by GreenNBlacko** [marcussacana/Specific-Games#22] opened 2021-03-08 09:10 UTC
There's a few issues with word wrapping(though it's not really that bad) and the backlog only works in the first chapter(it crashes the game when opening backlog on any other chapter).
and even when it does work, it shows up like this:
![image](https://user-images.githubusercontent.com/45263750/110299868-e8421e00-7ffe-11eb-86ac-9413042af260.png)

I'm also thinking if it's possible to override images so that UI elements could be translated?

**Comment by marcussacana** [comment] 2021-03-08 10:03
the CMVS Auto-Install currently only support english games.

**Comment by GreenNBlacko** [comment] 2021-03-08 10:25
I'm using the tool made for hapymaher fragmentation dreams

**Comment by GreenNBlacko** [comment] 2021-03-08 16:35
After tinkering around with text I found that if full width romaji is used in the string lists, it shows the text without doing that, however that would take a really long time to edit(I did try making a chars.lst file but as that also replaced the directory names, the game crashes) 
![image](https://user-images.githubusercontent.com/45263750/110350548-81dbf080-803c-11eb-9fb9-1541bab98552.png)
and as you can see the letters are too spaced apart and don't fit in the boxes, though that could probably be fixed with font width and height settings(?)

**Comment by GreenNBlacko** [comment] 2021-03-10 17:23
I managed to figure out what was causing the issue of the backlog making the text appear like this and well I found it out, it was the font. Basically the base font only featured japanese characters, therefor the engine didn't know what to do with them so it produced issues, by changing it to a font that includes english characters through cvmsconfig.exe(I used the translated version from hapymaher) 
![image](https://user-images.githubusercontent.com/45263750/110670293-e7afb000-81d5-11eb-8d29-69ebb6b68e17.png)
and now the text shows up properly(though I still need to space it to fit in the box)
![image](https://user-images.githubusercontent.com/45263750/110670354-f9915300-81d5-11eb-90e8-76e40861a2ea.png)
however, the backlog crashing the game issue still persists

**Comment by marcussacana** [comment] 2021-03-10 17:55
Good discovery indeed, sorry, I'm without time to work with my tools since I got an job, but if you find exactly what is happening maybe I can spend a bit of my time to create an hotfix.

**Comment by GreenNBlacko** [comment] 2021-03-10 18:05
hmm, so far I don't really have an idea, the logs don't really come up with anything, the only concerning thing would be this:
![image](https://user-images.githubusercontent.com/45263750/110675198-4d526b00-81db-11eb-85cb-fbe950814faf.png)
enabling debug mode doesn't really come up with anything significant either
![image](https://user-images.githubusercontent.com/45263750/110675722-e3869100-81db-11eb-9ba9-887ab5e50a16.png)

I'm attaching the log file in case you want to take a look at it
[SRL.log](https://github.com/marcussacana/Specific-Games/files/6117916/SRL.log)

**Comment by marcussacana** [comment] 2021-03-10 18:25
The Debug mode only work with self-builds, download the source, compile, and replace the game SRL.dll

**Comment by GreenNBlacko** [comment] 2021-03-11 09:45
After experimenting with the lines, I think I have found the culprit, though I can't really say for sure now
![image](https://user-images.githubusercontent.com/45263750/110767463-f55d4800-825e-11eb-8c7d-df0cb9a98846.png)
looking at the file, the first reload did not feature indents, but as soon as I tried opening the backlog with a line that has the indents, SRL freaks out starts replacing the line in tons of different ways, which may be what's causing the crash, but I'll be conducting further research on it after I've gotten rid of all the indentations on the files just to make sure that that's really the issue at hand

**Comment by marcussacana** [comment] 2021-03-11 09:58
Indeed it's strange, and is the last thing of the log as well, this made it more suspect...
I will give a try when I have a bit of time.

**Comment by marcussacana** [comment] 2021-03-13 16:33
Maybe tomorrow I will have a bit of free time to take a look

**Comment by marcussacana** [comment] 2021-03-14 17:36
I take a look here, then what I saw is..

1 - The backlog corruption isn't caused by the font, but as I initially thought, it is a problem with the Japanese version of the game.
Q: Then, Why worked with you?
R: Because you replaced the game executable with the English version, as we can see in your screenshot with the settings menu in english, they can be a different executable, but I supose you copied both executables to the game directory.

2 - The backlog crash, Yes, Looks like as you saw in the SRL.log that space in the begin of each line is really the cause of the crash, to fix that I did some checks in the SRL to ensure that he didn't duplicate the dialogue prefix, but that should be fixed as well by removing the space in the begin of each translation line in the .lst files.

And then, I published an update to the Hapymaher, take a look.

About the images, the SRL really don't support replace the game assets, and I don't have enought time to work in something like this because of my job, our friend @xmoeproject is who more know about this game file format, since he didn't created a repack and instead of that hooked the engine, Probably the engine has some checks that hinder the modification of the CPZ or the format is extremely complex for him to have taken the trouble to make a tool. 

By the way, in the game settings have those 2 options 
![image](https://user-images.githubusercontent.com/10576957/111073537-e7593280-84bd-11eb-94df-2ce96f32ac85.png)
Hmm... Suspect, right? well not sure anyway if disable that help with anything.

**Comment by GreenNBlacko** [comment] 2021-03-14 18:14
Another thing I wanted to ask
when I was using wordwrap, I noticed that it doesn't really do much, my question being, is it just me who doesn't know how to use it or does it just not work that good?

**Comment by marcussacana** [comment] 2021-03-14 18:18
Wordwrap works fine, only in some few games that don't works (like neptunia).
The builtin wordwrap it has made to monospaced fonts, games that use multi-spaced font the wordwrap don't will works.
and this isn't the case of this game.

to the Wordwrap works you must before anything setup the best font and size to your translation, then ensure to keep the hook enabled to force the game use allways the same settings, because changing it can affect the result, of course.

after that you should setup the wordwrap spacing in the SRL.ini, you must enabled the Wordwrap modifier and set the amount of charracters allowed per line in the game, then the SRL will do the trick to you.

**Comment by marcussacana** [comment] 2021-03-14 18:22
```ini
[Wordwrap]
UseRelativeWidth=false
RelativeWidth=if([Width]-([Width]/5) < 30, 50, [Width]-([Width]/5))
DefaultWidth=50
```
Relative width are made more for games, games usually have different places to show text, and this mean there are different of amount of character per line supported, the RelativeWidth will dynamically set the max amount based in the input line dialogue, then use this amount as reference to translation line.

The RelativeWidth as you can see is an expresion that are JIT evaulated and can dynamically return the result.

DefaultWidth is the most common setting, the max amount of characters per line, you only need change this one to visual novels usually.

```ini
[Modifiers]
Escape=false
MonoWordWrap=false
```
change the MonoWordWrap to true to enable it.

**Comment by GreenNBlacko** [comment] 2021-03-14 19:24
also looking at the start files it seems as though there is some kind of override for it
![image](https://user-images.githubusercontent.com/45263750/111081306-4beeae80-850b-11eb-9457-6b4ad4626727.png)
like there are the cpz archives and then a directory with the same name as the cpz(?) could be either just how it reads the archive contents or an override location, where if content is missing(like the cpz is not present) that it uses that directory for the files

in any case, I'll be trying it out

EDIT: nothing changes having the directory there and the game doesn't launch if you remove the cpz file

**Comment by marcussacana** [comment] 2021-03-14 20:10
yeah, don't will be that easy... and I said, i have no free time to create something better to this engine.

**Closed as completed** 2021-03-18 15:38 UTC
